#region License
/*
* Copyright 2013 Weswit Srl
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#endregion License

namespace Lightstreamer.DotNet.Client.Demo
{
    partial class FlowForm
    {

        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by Visual Studio

        private void InitializeComponent()
        {
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.label1 = new System.Windows.Forms.Label();
            this.lblStatus = new System.Windows.Forms.Label();
            this.lblItemCounter = new System.Windows.Forms.Label();
            this.cbxToggleStream = new System.Windows.Forms.CheckBox();
            this.tbLightstreamer = new System.Windows.Forms.TextBox();
            this.tbExcel = new System.Windows.Forms.TextBox();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 221F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 145F));
            this.tableLayoutPanel1.Controls.Add(this.label1, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.lblStatus, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.lblItemCounter, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.cbxToggleStream, 1, 2);
            this.tableLayoutPanel1.Controls.Add(this.tbLightstreamer, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.tbExcel, 0, 4);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 5;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 40F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 24F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 27F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 119F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 141F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(366, 321);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // label1
            // 
            this.label1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.label1.AutoSize = true;
            this.tableLayoutPanel1.SetColumnSpan(this.label1, 2);
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(15, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(335, 20);
            this.label1.TabIndex = 0;
            this.label1.Text = "Lightstreamer :: RTD Excel Demo :: .NET";
            // 
            // lblStatus
            // 
            this.lblStatus.AutoSize = true;
            this.tableLayoutPanel1.SetColumnSpan(this.lblStatus, 2);
            this.lblStatus.Location = new System.Drawing.Point(3, 40);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(162, 13);
            this.lblStatus.TabIndex = 1;
            this.lblStatus.Text = "Connection status: disconnected";
            // 
            // lblItemCounter
            // 
            this.lblItemCounter.AutoSize = true;
            this.lblItemCounter.Location = new System.Drawing.Point(3, 64);
            this.lblItemCounter.Name = "lblItemCounter";
            this.lblItemCounter.Size = new System.Drawing.Size(109, 13);
            this.lblItemCounter.TabIndex = 2;
            this.lblItemCounter.Text = "Lightstreamer items: 0";
            // 
            // cbxToggleStream
            // 
            this.cbxToggleStream.AutoSize = true;
            this.cbxToggleStream.Checked = true;
            this.cbxToggleStream.CheckState = System.Windows.Forms.CheckState.Checked;
            this.cbxToggleStream.Location = new System.Drawing.Point(224, 67);
            this.cbxToggleStream.Name = "cbxToggleStream";
            this.cbxToggleStream.Size = new System.Drawing.Size(124, 17);
            this.cbxToggleStream.TabIndex = 9;
            this.cbxToggleStream.Text = "Data stream to Excel";
            this.cbxToggleStream.UseVisualStyleBackColor = true;
            this.cbxToggleStream.CheckedChanged += new System.EventHandler(this.cbxToggleStream_CheckedChanged);
            // 
            // tbLightstreamer
            // 
            this.tbLightstreamer.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.tableLayoutPanel1.SetColumnSpan(this.tbLightstreamer, 2);
            this.tbLightstreamer.Location = new System.Drawing.Point(3, 94);
            this.tbLightstreamer.Multiline = true;
            this.tbLightstreamer.Name = "tbLightstreamer";
            this.tbLightstreamer.ReadOnly = true;
            this.tbLightstreamer.Size = new System.Drawing.Size(360, 113);
            this.tbLightstreamer.TabIndex = 10;
            // 
            // tbExcel
            // 
            this.tbExcel.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.tableLayoutPanel1.SetColumnSpan(this.tbExcel, 2);
            this.tbExcel.Location = new System.Drawing.Point(3, 213);
            this.tbExcel.Multiline = true;
            this.tbExcel.Name = "tbExcel";
            this.tbExcel.ReadOnly = true;
            this.tbExcel.Size = new System.Drawing.Size(360, 105);
            this.tbExcel.TabIndex = 11;
            // 
            // FlowForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(366, 321);
            this.ControlBox = false;
            this.Controls.Add(this.tableLayoutPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "FlowForm";
            this.Text = "Lightstreamer :: RTD Demo :: Excel";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FlowForm_FormClosing);
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.FlowForm_FormClosed);
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.Label lblItemCounter;
        private System.Windows.Forms.CheckBox cbxToggleStream;
        private System.Windows.Forms.TextBox tbLightstreamer;
        private System.Windows.Forms.TextBox tbExcel;

    }
}

